version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  gateway:
    build:
      context: .
      dockerfile: packages/gateway/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - auth-service
      - user-service
      - chat-service
      - redis
      - rabbitmq

  auth-service:
    build:
      context: .
      dockerfile: packages/auth-service/Dockerfile
    depends_on:
      - redis
      - rabbitmq
      - postgres

  user-service:
    build:
      context: .
      dockerfile: packages/user-service/Dockerfile
    depends_on:
      - postgres
      - rabbitmq

  chat-service:
    build:
      context: .
      dockerfile: packages/chat-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - redis
      - rabbitmq

  web-app:
    build:
      context: .
      dockerfile: packages/web-app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - gateway

volumes:
  postgres_data:
  redis_data: 