version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  gateway:
    build:
      context: .
      dockerfile: packages/gateway/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./packages/gateway:/app/packages/gateway

  web-app:
    build:
      context: .
      dockerfile: packages/web-app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3003
    volumes:
      - ./packages/web-app:/app/packages/web-app
      - /app/node_modules

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongodb_data:/data/db

  psy-service:
    build:
      context: .
      dockerfile: packages/psy-service/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/psy_db?authSource=admin
      - PSY_SERVICE_PORT=3004
    depends_on:
      - mongodb
    volumes:
      - ./packages/psy-service:/app/packages/psy-service
      - /app/node_modules

volumes:
  redis_data:
  rabbitmq_data:
  mongodb_data: 