version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: psychology_portal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  gateway:
    build:
      context: .
      dockerfile: packages/gateway/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - auth-service
      - content-service
      - chat-service
      - redis
      - rabbitmq

  auth-service:
    build:
      context: .
      dockerfile: packages/auth-service/Dockerfile
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/psychology_portal?authSource=admin
    depends_on:
      - redis
      - rabbitmq
      - mongodb

  content-service:
    build:
      context: .
      dockerfile: packages/content-service/Dockerfile
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/psychology_portal?authSource=admin
    depends_on:
      - mongodb
      - rabbitmq

  chat-service:
    build:
      context: .
      dockerfile: packages/chat-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/psychology_portal?authSource=admin
    depends_on:
      - redis
      - rabbitmq
      - mongodb

  analytics-service:
    build:
      context: .
      dockerfile: packages/analytics-service/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/psychology_portal?authSource=admin

  web-app:
    build:
      context: .
      dockerfile: packages/web-app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - gateway

volumes:
  redis_data:
  mongodb_data: 